DATA MANIPULATION AND ANALYSIS WITH PANDAS

Data manipulation  and analysis are key tasks in any data analysis project. Pandas provides a wide range of functions for data manipulation and analysis making it easier to clean, transform and extracts insights from data. In this lesson we will cover various data manipulation and analysis techniques using Pandas.

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('Details.csv')
df.head(5)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

In [4]:
df.describe()

            Amount      Profit     Quantity
count  1500.000000  1500.00000  1500.000000
mean    291.847333    24.64200     3.743333
std     461.924620   168.55881     2.184942
min       4.000000 -1981.00000     1.000000
25%      47.750000   -12.00000     2.000000
50%     122.000000     8.00000     3.000000
75%     326.250000    38.00000     5.000000
max    5729.000000  1864.00000    14.000000

In [5]:
df.dtypes

Order ID        object
Amount           int64
Profit           int64
Quantity         int64
Category        object
Sub-Category    object
PaymentMode     object
dtype: object

In [8]:
##Handling missing values
df.isnull().any()

Order ID        False
Amount          False
Profit          False
Quantity        False
Category        False
Sub-Category    False
PaymentMode     False
dtype: bool

In [9]:
df.isnull().sum()

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
PaymentMode     0
dtype: int64

In [10]:
##fill valuse since in the above data we don't have missing values so we can't fill

# df_filled= df.fillna(0)

In [11]:
### filling missing values with the mean of the column
# df['Sales_fillNA']=df['Sales'].fillna(df['Sales'].mean())
# df

In [12]:
df.dtypes

Order ID        object
Amount           int64
Profit           int64
Quantity         int64
Category        object
Sub-Category    object
PaymentMode     object
dtype: object

In [ ]:
## renaming columns
# df=df.rename(columns={'Date':'Sale Date'})
# df.head()

In [ ]:
## change datatypes
# df['value_new']=df['Value'].fillna(df['Value'].mean().astype(int)
# df.head()  float to int datatypes

In [13]:
# df['New Value'] =df['Value'].apply(lambda x:x*2)

In [ ]:
##Data Aggregating and grouping 
# grouped_mean=df.groupby('Product')['value'].mean()
# print(grouped_mean)

In [ ]:
# groupedz_sum=df.groupby(['Product','Region'])['value'].sum()
# print(grouped_sum)

In [ ]:
# groupedz_sum=df.groupby(['Product','Region'])['value'].mean()

In [ ]:
##aggregate multiple functions 
# grouped_agg=df.groupby('Region')['value'].agg(['mean','sum','count'])
# grouped_agg

In [21]:
### merging and joining dataframes
# create sample dataframes
df1=pd.DataFrame({'Key' :['A','B','C'],'Value1':[1,2,3]})
df2=pd.DataFrame({'Key' :['A','B','D'],'Value1':[4,5,6]})

In [22]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [23]:
df2

  Key  Value1
0   A       4
1   B       5
2   D       6

In [25]:
## merge dataframe on the key column
pd.merge(df1,df2,on="Key",how="inner")

  Key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [26]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1_x  Value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0

In [27]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1_x  Value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [28]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1_x  Value1_y
0   A       1.0         4
1   B       2.0         5
2   D       NaN         6